# Generated by Django 2.2.6 on 2019-10-14 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('condition_description', models.TextField(blank=True, default='This is where you enter the trigger condition description.')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('effect_description', models.TextField(blank=True, default='This is where you enter the effect description.')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, default='This is where you enter an item description.', max_length=200)),
                ('long_description', models.TextField(blank=True, default='This is where you enter long rules text.')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='{}')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Condition')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Effect')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Item')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='item',
            name='owners',
            field=models.ManyToManyField(to='engine.Player'),
        ),
        migrations.AddField(
            model_name='item',
            name='triggers',
            field=models.ManyToManyField(through='engine.Trigger', to='engine.Condition'),
        ),
    ]
