# Generated by Django 2.2.6 on 2019-10-14 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engine', '0003_auto_20191014_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('condition_description', models.TextField(blank=True, default='This is where you enter the trigger condition description.')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('effect_description', models.TextField(blank=True, default='This is where you enter the effect description.')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rules', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, default='This is where you enter an item description.', max_length=200)),
                ('long_description', models.TextField(blank=True, default='This is where you enter long rules text.')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='{}')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Condition')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Effect')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Game')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('recieveEmails', models.BooleanField(default=False)),
                ('currentPlayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('username',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='owners',
            field=models.ManyToManyField(to='engine.Player'),
        ),
        migrations.AddField(
            model_name='item',
            name='triggers',
            field=models.ManyToManyField(through='engine.Trigger', to='engine.Condition'),
        ),
    ]
