# Generated by Django 2.2.6 on 2019-10-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20191014_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
