# Generated by Django 2.2.6 on 2019-10-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20191014_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='game',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='item',
            name='triggers',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='game',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='item',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
    ]
