# Generated by Django 2.2.6 on 2019-10-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20191017_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='can_join',
            field=models.BooleanField(default=True),
        ),
    ]
