# Generated by Django 2.2.6 on 2019-10-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_game_can_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='recieveEmails',
            new_name='receiveEmails',
        ),
    ]
